name: Publish

on:
  push:
    tags:
      - "v*"
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Update version tag
        run: |
          echo "tag is ${{ github.ref }}"
          # refs/tags/vx.y.z -> vx.y.z -> x.y.z
          echo "cutted tag is `echo ${{ github.ref }} | cut -d / -f 3 | cut -c 2-`"
          sed -i "s/unknown/`echo ${{ github.ref }} | cut -d / -f 3 | cut -c 2-`/" setup.py
          sed -i "s/unknown/`echo ${{ github.ref }} | cut -d / -f 3 | cut -c 2-`/" tagls/__init__.py
          cat setup.py
      - name: Create sdist
        run: |
          python3 setup.py sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
